use_frameworks!
platform :ios, '9.3'


target 'UITestKit_Example' do

  pod 'Cartography'

  target 'UITestKit_ExampleTests' do
    inherit! :search_paths
    pod 'UITestKit', :path => '../'

  end
end
